version: '3.8'

volumes:
  postgres_data:
  static_value:
  media_value:
  frontend_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: dfadeevzld/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: dfadeevzld/foodgram_frontend:v1.0
    volumes:
      - frontend_data:/app/build/
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_data:/usr/share/nginx/html/
      - ./backend/docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./backend/docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
    restart: always
    depends_on:
      - backend
      - frontend
