# Generated by Django 3.0.14 on 2021-08-05 05:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ингредиент')),
                ('slug', models.SlugField(unique=True, verbose_name='slug ингредиентов рецепта')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(unique=True, verbose_name='slug Тега')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Рецепт блюда')),
                ('Cooking_time', models.PositiveIntegerField(verbose_name='Время приготовления')),
                ('rating', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, 'Рейтинг не может быть ниже 1'), django.core.validators.MaxValueValidator(5, 'Рейтинг не может быть выше 5')], verbose_name='Рейтинг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание рецепта')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient', to='recipes.Ingredient')),
                ('tag', models.ManyToManyField(to='recipes.Tag')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
